[2024-12-12T09:15:29.277+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:15:25.782340+00:00 [queued]>
[2024-12-12T09:15:29.290+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:15:25.782340+00:00 [queued]>
[2024-12-12T09:15:29.290+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-12T09:15:29.309+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt> on 2024-12-12 09:15:25.782340+00:00
[2024-12-12T09:15:29.317+0000] {standard_task_runner.py:57} INFO - Started process 6514 to run task
[2024-12-12T09:15:29.320+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_example', 'run_dbt', 'manual__2024-12-12T09:15:25.782340+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/dbt_duckdb_test.py', '--cfg-path', '/tmp/tmprlug6jq7']
[2024-12-12T09:15:29.322+0000] {standard_task_runner.py:85} INFO - Job 162: Subtask run_dbt
[2024-12-12T09:15:29.389+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:15:25.782340+00:00 [running]> on host 4bdf037cbc68
[2024-12-12T09:15:29.506+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_example' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T09:15:25.782340+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T09:15:25.782340+00:00'
[2024-12-12T09:15:29.508+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T09:15:29.510+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models business_transformed']
[2024-12-12T09:15:29.525+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T09:15:32.285+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-12-12T09:15:32.286+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-12-12T09:15:32.286+0000] {subprocess.py:93} INFO - 
[2024-12-12T09:15:32.287+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/home/***/.dbt' does not exist.
[2024-12-12T09:15:32.549+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-12T09:15:32.560+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-12T09:15:32.564+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag_example, task_id=run_dbt, execution_date=20241212T091525, start_date=20241212T091529, end_date=20241212T091532
[2024-12-12T09:15:32.589+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 162 for task run_dbt (Bash command failed. The command returned a non-zero exit code 2.; 6514)
[2024-12-12T09:15:32.628+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-12T09:15:32.660+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
