[2024-12-12T09:20:33.964+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:15:25.782340+00:00 [queued]>
[2024-12-12T09:20:33.972+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:15:25.782340+00:00 [queued]>
[2024-12-12T09:20:33.973+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-12T09:20:33.986+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt> on 2024-12-12 09:15:25.782340+00:00
[2024-12-12T09:20:33.992+0000] {standard_task_runner.py:57} INFO - Started process 2003 to run task
[2024-12-12T09:20:33.995+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_example', 'run_dbt', 'manual__2024-12-12T09:15:25.782340+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/dbt_duckdb_test.py', '--cfg-path', '/tmp/tmprl9r5p4j']
[2024-12-12T09:20:33.997+0000] {standard_task_runner.py:85} INFO - Job 170: Subtask run_dbt
[2024-12-12T09:20:34.047+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:15:25.782340+00:00 [running]> on host 15c1365b7b27
[2024-12-12T09:20:34.122+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_example' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T09:15:25.782340+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T09:15:25.782340+00:00'
[2024-12-12T09:20:34.125+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T09:20:34.126+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd my_dbt_project && dbt run --models business_transformed']
[2024-12-12T09:20:34.135+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T09:20:34.136+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: my_dbt_project: No such file or directory
[2024-12-12T09:20:34.136+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-12T09:20:34.147+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-12T09:20:34.151+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_dag_example, task_id=run_dbt, execution_date=20241212T091525, start_date=20241212T092033, end_date=20241212T092034
[2024-12-12T09:20:34.163+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 170 for task run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 2003)
[2024-12-12T09:20:34.209+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-12T09:20:34.231+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
