[2024-12-04T08:44:28.147+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-04T08:39:24.363639+00:00 [queued]>
[2024-12-04T08:44:28.157+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-04T08:39:24.363639+00:00 [queued]>
[2024-12-04T08:44:28.158+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-04T08:44:28.172+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): download_and_extract_kaggle_data> on 2024-12-04 08:39:24.363639+00:00
[2024-12-04T08:44:28.179+0000] {standard_task_runner.py:57} INFO - Started process 2206 to run task
[2024-12-04T08:44:28.182+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_duckdb', 'download_and_extract_kaggle_data', 'manual__2024-12-04T08:39:24.363639+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/business_etl_v1.py', '--cfg-path', '/tmp/tmpyejuf2n7']
[2024-12-04T08:44:28.184+0000] {standard_task_runner.py:85} INFO - Job 101: Subtask download_and_extract_kaggle_data
[2024-12-04T08:44:28.230+0000] {task_command.py:410} INFO - Running <TaskInstance: kaggle_to_duckdb.download_and_extract_kaggle_data manual__2024-12-04T08:39:24.363639+00:00 [running]> on host e919c4bb8fbe
[2024-12-04T08:44:28.331+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_duckdb' AIRFLOW_CTX_TASK_ID='download_and_extract_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T08:39:24.363639+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T08:39:24.363639+00:00'
[2024-12-04T08:44:28.674+0000] {logging_mixin.py:150} INFO - Dataset URL: https://www.kaggle.com/datasets/mannmann2/fortune-500-corporate-headquarters
[2024-12-04T08:44:28.674+0000] {logging_mixin.py:150} INFO - License(s): CC0-1.0
[2024-12-04T08:44:29.161+0000] {logging_mixin.py:150} INFO - fortune-500-corporate-headquarters.zip: Skipping, found more recently modified local copy (use --force to force download)
[2024-12-04T08:44:29.162+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/business_etl_v1.py", line 35, in download_and_extract_dataset
    raise FileNotFoundError(f"{zip_name}.zip not found after download.")
FileNotFoundError: fortune-500-HQ.zip not found after download.
[2024-12-04T08:44:29.177+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=kaggle_to_duckdb, task_id=download_and_extract_kaggle_data, execution_date=20241204T083924, start_date=20241204T084428, end_date=20241204T084429
[2024-12-04T08:44:29.190+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 101 for task download_and_extract_kaggle_data (fortune-500-HQ.zip not found after download.; 2206)
[2024-12-04T08:44:29.200+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-04T08:44:29.227+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
