[2024-12-12T09:10:36.501+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:05:28.791712+00:00 [queued]>
[2024-12-12T09:10:36.518+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:05:28.791712+00:00 [queued]>
[2024-12-12T09:10:36.519+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-12T09:10:36.541+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): run_dbt> on 2024-12-12 09:05:28.791712+00:00
[2024-12-12T09:10:36.548+0000] {standard_task_runner.py:57} INFO - Started process 4330 to run task
[2024-12-12T09:10:36.552+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag_example', 'run_dbt', 'manual__2024-12-12T09:05:28.791712+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/dbt_duckdb_test.py', '--cfg-path', '/tmp/tmpy65k2p8h']
[2024-12-12T09:10:36.555+0000] {standard_task_runner.py:85} INFO - Job 160: Subtask run_dbt
[2024-12-12T09:10:36.633+0000] {task_command.py:410} INFO - Running <TaskInstance: dbt_dag_example.run_dbt manual__2024-12-12T09:05:28.791712+00:00 [running]> on host 4bdf037cbc68
[2024-12-12T09:10:36.746+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_dag_example' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T09:05:28.791712+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T09:05:28.791712+00:00'
[2024-12-12T09:10:36.748+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T09:10:36.749+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models business_transformed']
[2024-12-12T09:10:36.761+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T09:10:39.604+0000] {subprocess.py:93} INFO - Usage: dbt run [OPTIONS]
[2024-12-12T09:10:39.606+0000] {subprocess.py:93} INFO - Try 'dbt run -h' for help.
[2024-12-12T09:10:39.607+0000] {subprocess.py:93} INFO - 
[2024-12-12T09:10:39.608+0000] {subprocess.py:93} INFO - Error: Invalid value for '--profiles-dir': Path '/home/***/.dbt' does not exist.
[2024-12-12T09:10:39.839+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-12T09:10:39.867+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-12T09:10:39.872+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dbt_dag_example, task_id=run_dbt, execution_date=20241212T090528, start_date=20241212T091036, end_date=20241212T091039
[2024-12-12T09:10:39.904+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 160 for task run_dbt (Bash command failed. The command returned a non-zero exit code 2.; 4330)
[2024-12-12T09:10:39.927+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-12T09:10:39.976+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
